base_config: base.yaml

perception:
  use_ground_truth: false
  scene_manager:
    tsdf_voxel_size: 0.005
    tsdf_color_type: rgb
    tsdf_trunc_ratio: 4.0
    tsdf_max_depth: 3.0
    bbox_min_match_th: 0.1
    bbox_drop_base_margin: true
    bbox_base_margin: 0.01

grounding_model:
  model_name: glip
  model_args: {}
  
joint_predction:
  method: ground_truth # TODO: change it to the joint prediction model 
  model_params:
    service_name: /gazebo/get_joints_axes

grasp_detection:
  model_name: anygrasp
  model_params:
    service_name: /detect_grasps
  visualize: false
  verbose: false

lmps:
  tabletop_ui:
    class: LMPOpenAI
    model: gpt-3.5-turbo-16k
    messages: message_tabletop_perception
