base_config: text_base.yaml

grounding_model: {} # not used in text-only setting

grasp_detection:
  model_name: anygrasp
  model_params:
    service_name: /detect_grasps
  visualize: false
  verbose: false

lmps:
  tabletop_ui:
    class: LMPGemini
    model: gemini-pro
    messages: message_tabletop_text_few_shot

  fgen:
    class: LMPFGenGemini
    model: gemini-pro
    messages: message_fgen_few_shot